version:     "0018b--03-Aug-2021"
copyright:   "2021-2021"
description:
  Stephen Docy's
  Personal Website
disclaimer:
  
keywords:    ""
navbarlinks:
- navbar:    "Home"
  link:      "/"
- navbar:    "Links"
  link:      "/LINKS/"
- navbar:    "About Website"
  link:      "/ABOUT/"
title:       "Stephen Docy's Personal Website"
lang:        "en-US"
author:      "Stephen Docy"
address:     ""
sitemap:     "true"
markdown:    "kramdown"
defaults:
- scope:
    path:    ""
  values:
    layout:  "default"
github:
- metadata
plugins:
- jekyll-sitemap
- jekyll-seo-tag
google_analytics: "UA-89852122-15"

urlweb:           "https://sdocy503.github.io/"
urlcontact:       "TBA"
urlgithub:        "https://github.com/ThisIsHowMeDoIt/template"


